### ISSUE TITLE
Store binary with latin1

### ISSUE THREAD

**Issue by maxlapshin** [alexeyr/erlang-sqlite3#43]
User came with user_agent  <<"^PUjC^PUjC°æ°">> 

Sqlite driver failed trying to write it to database:

```
** exception exit: {{badarg,[{re,replace,
                                 [<<"^PUjC^PUjC°æ°">>,"'","''",[global,unicode]],
                                 [{file,"re.erl"},{line,357}]},
                             {sqlite3_lib,value_to_sql,1,
                                          [{file,"libs/sqlite3/src/sqlite3_lib.erl"},{line,107}]},
                             {sqlite3_lib,map_intersperse,3,
                                          [{file,"libs/sqlite3/src/sqlite3_lib.erl"},{line,311}]},
```

I don't know what is the right way to handle such input data?  It is a text, but escape function is more targeted to a unicode list.

Maybe I should store all user input as a blob?

Or add a special case when I pass binary to use not re, but binary:replace?

**Comment by alexeyr** [comment]
Looking at `re`'s documentation, maybe just remove `unicode` option? If it works, please make a pull request with a test.

**Comment by maxlapshin** [comment]
No,  unicode option is mandatory for your test with [1048, 1056, ….]  unicode list.

I’ve made such patch at my local branch:

```
-escape(IoData) -> re:replace(IoData, "'", "''", [global, unicode]).
+escape(Bin) when is_binary(Bin) -> binary:replace(Bin, <<"'">>, <<"''">>, [global]);
+escape(IoData) -> unicode:characters_to_binary(re:replace(IoData, "'", "''", [global, unicode])).
```

What do you think about it?

**Comment by alexeyr** [comment]
Instead of `characters_to_binary`, we can use `{return, binary}` option. But why is this useful?

**Comment by maxlapshin** [comment]
When you write  UnicodeString = [1102,1085,1080,1082,1086,1076]  to sqlite, you ask to write one form of unicode, when byte sequence is transformed to codepoints or glyphs (don't know for sure).

When you ask to write  <<209,142,208,189,208,184,208,186,208,190,208,180>>, it means that your internal representation of unicode string is already translated to utf-8 representation with bytes.

So when we get <<"^PUjC^PUjC°æ°">> from caller, we don't know for sure what is it, because it seems to be an invalid unicode, but a valid byte sequence (because it is already binary).

**Comment by alexeyr** [comment]
I mean, why do we want `escape` to return a binary in list case instead of an iolist.

Also, this won't work with iolist containing latin-1 binaries. I think this should be fixed correctly. In a moment.

**Comment by alexeyr** [comment]
Please check if https://github.com/alexeyr/erlang-sqlite3/tree/issue-43 works for you.

**Comment by alexeyr** [comment]
@maxlapshin Did you have an opportunity to check it yet?
